version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: apprendsmoi-mongo
    ports:
      - "${MONGODB__PORT:-27017}:27017"
    volumes:
      - mongodata:/data/db
    environment:
      # If you want to enable auth, set these and update connection string
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB__ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB__ROOT_PASSWORD}

volumes:
  mongodata:
